name: 💡 Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide details about what you'd like to see.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - UI/UX Improvement
        - New Channel Management Rule
        - Observability/Metrics
        - Automation/Integration
        - Security Enhancement
        - Performance Improvement
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to your workflow?
      options:
        - High - Blocking my workflow
        - Medium - Would significantly improve my workflow
        - Low - Nice to have
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or limitation you're experiencing
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to happen?
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: Describe any alternative solutions or workarounds you've tried

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case
      placeholder: |
        Help us understand how you would use this feature:
        - What's your Enterprise Grid setup like?
        - How many workspaces do you manage?
        - What's your current workflow?

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how this would work
      placeholder: |
        CLI commands, UI mockups, configuration examples, etc.

  - type: checkboxes
    id: roadmap
    attributes:
      label: Roadmap Alignment
      description: Is this feature on our roadmap?
      options:
        - label: I've checked the [roadmap](https://github.com/regardt-meyer/slack-channel-manager/blob/master/docs/ROADMAP.md)
        - label: This is a new idea not currently on the roadmap
        - label: This enhances an existing roadmap item

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to help implement this feature?
      options:
        - label: I'd like to help implement this feature
        - label: I can provide testing and feedback
        - label: I can help with documentation